cat << 'EOF' >> /root/.zshrc
alias c='clear'
alias r2='ros2'
alias r2r='ros2 run'
alias r2i='ros2 info'
alias rb='rm -rf build install log'
alias cb='colcon build --symlink-install'
alias cbp='colcon build --symlink-install --packages-select'
alias si='source install/setup.zsh'
alias r2sl='ros2 service list'
alias r2st='ros2 service type'
alias r2sr='ros2 service call'
alias r2pc='ros2 pkg create'
alias r2pcpy='ros2 pkg create --build-type ament_python'
alias r2is='ros2 interface show'
alias r2l='ros2 launch'
alias r2br='ros2 bag record'
alias r2bi='ros2 bag info'
alias r2bp='ros2 bag play'
alias r2tl='ros2 topic list'
alias r2al='ros2 action list'
alias r2ai='ros2 action info'
alias r2asg='ros2 action send_goal'
EOF